// Every playable map set. `source` decides where geometry comes from:
//   ne-admin0  — Natural Earth 50m countries
//   ne-admin1  — Natural Earth 10m states/provinces, filtered by `adm0`
//   geoboundaries — a cached geoBoundaries download (used where NE is incomplete)
export const SETS = [
  {
    id: 'world-countries',
    title: 'Страны мира',
    group: 'Мир',
    unitPlural: 'стран',
    source: { kind: 'ne-admin0' },
    projection: 'equalEarth',
    // Built from Natural Earth 10m: at 50m the median area error against
    // published figures was 3.7%, here it is 1.6% for ~120 KB more.
    simplify: '4%',
    modes: ['learn', 'locate', 'flag', 'capital'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'slovenia-municipalities',
    title: 'Общины Словении',
    group: 'Административные единицы',
    country: 'Словения',
    unitPlural: 'общин',
    source: { kind: 'geoboundaries', file: 'gb_SVN_ADM2.geojson', isoPrefix: 'SI-' },
    // geoBoundaries extends coastal units into territorial waters.
    clipToLand: true,
    projection: 'mercator',
    simplify: '12%',
    modes: ['learn', 'locate'],
    attribution: 'geoBoundaries (CC BY 4.0)',
  },
  {
    id: 'timor-municipalities',
    title: 'Муниципалитеты Восточного Тимора',
    group: 'Административные единицы',
    country: 'Восточный Тимор',
    unitPlural: 'муниципалитетов',
    source: { kind: 'ne-admin1', adm0: 'TLS' },
    projection: 'mercator',
    simplify: '10%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'myanmar-states',
    title: 'Штаты и области Мьянмы',
    group: 'Административные единицы',
    country: 'Мьянма',
    unitPlural: 'штатов и областей',
    source: { kind: 'ne-admin1', adm0: 'MMR' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'niger-regions',
    title: 'Регионы Нигера',
    group: 'Административные единицы',
    country: 'Нигер',
    unitPlural: 'регионов',
    source: { kind: 'ne-admin1', adm0: 'NER' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'mali-regions',
    title: 'Регионы Мали',
    group: 'Административные единицы',
    country: 'Мали',
    unitPlural: 'регионов',
    source: { kind: 'ne-admin1', adm0: 'MLI' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'chad-provinces',
    title: 'Регионы Чада',
    group: 'Административные единицы',
    country: 'Чад',
    unitPlural: 'регионов',
    source: { kind: 'geoboundaries', file: 'gb_TCD_ADM1.geojson', isoPrefix: 'TD-' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'geoBoundaries (CC BY 4.0)',
  },
  {
    id: 'car-prefectures',
    title: 'Префектуры ЦАР',
    group: 'Административные единицы',
    country: 'Центральноафриканская Республика',
    unitPlural: 'префектур',
    source: { kind: 'ne-admin1', adm0: 'CAF' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'south-sudan-states',
    title: 'Штаты Южного Судана',
    group: 'Административные единицы',
    country: 'Южный Судан',
    unitPlural: 'штатов',
    source: { kind: 'ne-admin1', adm0: 'SDS' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
]
