// Every playable map set. `source` decides where geometry comes from:
//   ne-admin0  — Natural Earth 50m countries
//   ne-admin1  — Natural Earth 10m states/provinces, filtered by `adm0`
//   geoboundaries — a cached geoBoundaries download (used where NE is incomplete)
export const SETS = [
  {
    id: 'world-countries',
    title: 'Страны мира',
    group: 'Мир',
    unitPlural: 'стран',
    source: { kind: 'ne-admin0' },
    projection: 'equalEarth',
    // Built from Natural Earth 10m: at 50m the median area error against
    // published figures was 3.7%, here it is 1.6% for ~120 KB more.
    simplify: '4%',
    modes: ['learn', 'locate', 'flag', 'capital'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'russia-subjects',
    title: 'Субъекты России',
    group: 'Административные единицы',
    country: 'Россия',
    unitPlural: 'субъектов',
    source: {
      kind: 'ne-admin1',
      adm0: 'RUS',
      // Natural Earth files these four under Ukraine; the set is built to the
      // composition of 89 subjects, so they are pulled in by ISO code.
      include: ['UA-14', 'UA-09', 'UA-23', 'UA-65'],
      // An unnamed placeholder polygon of 0.008 deg² that NE ships for Russia.
      exclude: ['RU-X01~'],
    },
    // Russia crosses the antimeridian, so an unrotated projection would smear it
    // across the whole width. Conic equal-area centred on 100°E keeps it readable.
    projection: 'conic',
    rotate: [-100, 0],
    parallels: [50, 70],
    // 5% put Vladivostok 7 km outside its own coastline; 10% brings it back in.
    simplify: '10%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'ukraine-oblasts',
    title: 'Области Украины',
    group: 'Административные единицы',
    country: 'Украина',
    unitPlural: 'единиц',
    source: {
      kind: 'ne-admin1',
      adm0: 'UKR',
      // The four oblasts that the set of Russian subjects already covers, so the
      // two sets stay disjoint. Crimea and Sevastopol are filed under Russia in
      // Natural Earth and are therefore absent here as well.
      exclude: ['UA-14', 'UA-09', 'UA-23', 'UA-65'],
    },
    projection: 'mercator',
    simplify: '10%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'slovenia-municipalities',
    title: 'Общины Словении',
    group: 'Административные единицы',
    country: 'Словения',
    unitPlural: 'общин',
    source: { kind: 'geoboundaries', file: 'gb_SVN_ADM2.geojson', isoPrefix: 'SI-' },
    // geoBoundaries extends coastal units into territorial waters.
    clipToLand: true,
    projection: 'mercator',
    simplify: '12%',
    modes: ['learn', 'locate'],
    attribution: 'geoBoundaries (CC BY 4.0)',
  },
  {
    id: 'timor-municipalities',
    title: 'Муниципалитеты Восточного Тимора',
    group: 'Административные единицы',
    country: 'Восточный Тимор',
    unitPlural: 'муниципалитетов',
    source: { kind: 'ne-admin1', adm0: 'TLS' },
    projection: 'mercator',
    simplify: '10%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'myanmar-states',
    title: 'Штаты и области Мьянмы',
    group: 'Административные единицы',
    country: 'Мьянма',
    unitPlural: 'штатов и областей',
    source: { kind: 'ne-admin1', adm0: 'MMR' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'niger-regions',
    title: 'Регионы Нигера',
    group: 'Административные единицы',
    country: 'Нигер',
    unitPlural: 'регионов',
    source: { kind: 'ne-admin1', adm0: 'NER' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'mali-regions',
    title: 'Регионы Мали',
    group: 'Административные единицы',
    country: 'Мали',
    unitPlural: 'регионов',
    source: { kind: 'ne-admin1', adm0: 'MLI' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'chad-provinces',
    title: 'Регионы Чада',
    group: 'Административные единицы',
    country: 'Чад',
    unitPlural: 'регионов',
    source: { kind: 'geoboundaries', file: 'gb_TCD_ADM1.geojson', isoPrefix: 'TD-' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'geoBoundaries (CC BY 4.0)',
  },
  {
    id: 'car-prefectures',
    title: 'Префектуры ЦАР',
    group: 'Административные единицы',
    country: 'Центральноафриканская Республика',
    unitPlural: 'префектур',
    source: { kind: 'ne-admin1', adm0: 'CAF' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
  {
    id: 'south-sudan-states',
    title: 'Штаты Южного Судана',
    group: 'Административные единицы',
    country: 'Южный Судан',
    unitPlural: 'штатов',
    source: { kind: 'ne-admin1', adm0: 'SDS' },
    projection: 'mercator',
    simplify: '8%',
    modes: ['learn', 'locate'],
    attribution: 'Natural Earth (public domain)',
  },
]
